set guifont=AndaleMono:h18

function RandomColorScheme()
  let mycolors = split(globpath(&rtp,"**/colors/*.vim"),"\n") 
  exe 'so ' . mycolors[localtime() % len(mycolors)]
  unlet mycolors
endfunction

if getcwd() =~ '/worktrees\(/\|$\)'
    colorscheme morning
elseif getcwd() =~ '^' . expand('~/src') . '\(/\|$\)'
    call RandomColorScheme()
else
    colorscheme peachpuff
endif

:command NewColor call RandomColorScheme()
