execute pathogen#infect()

syntax on
filetype plugin indent on
set hlsearch
set incsearch
set listchars=tab:»·,trail:·
set list
set ruler

nnoremap <CR> :noh<CR><CR>
"nnoremap <F8> :SyntasticCheck flake8 pylint mypy<CR>
nnoremap <F8> :ALELint<CR>

let g:syntastic_python_checkers=['flake8']

let g:airline_theme='bubblegum'
let g:recutils_no_folding=1

let zotcite_conceallevel = 0

let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1

let g:netrw_liststyle=1

nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)

autocmd bufreadpre *.md setlocal textwidth=88

" set fencs=ucs-bom,utf-16le,utf-8,default,latin1
