[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
   "ANN101",
   "ANN102",
   "D105",
   "D107",
   "D203",
   "D213",
   "EM101",
   "EM102",
   "S101",
   "S311",
   "S324",
   "SIM102",
   "T201",
   "TRY003" ,
]

[tool.ruff.lint.isort]
force-single-line = true
