#!/bin/sh

for f in t*.tagged.txt; do
	u=${f}.utf8
	echo "Converting $f -> $u"
	iconv -f UTF-16LE $f > ${u}
done

for f in t*docx; do
	d=${f}.unzipped
	unzip -o $f -d $d
	for x in `find $d -name \*.xml`; do
		xml-fmt $x > ${x}.fmt && mv -f ${x}.fmt $x
	done
done

# TODO: odt
# TODO: idml
# TODO: fodt?

