#!/usr/bin/env python3
"""Erez Volk's Restic Backup."""
import argparse
import os.path
import shlex
import subprocess
import typing as t
from pathlib import Path
from tempfile import TemporaryDirectory

__TODO__ = """
- Case where there's more than one disk attached
- A restore option
- Backup multiple machines
"""


EXCLUDE = """
$HOME/Library/*

!$HOME/Library/Fonts

!$HOME/Library/Preferences
$HOME/Library/Preferences/*
!$HOME/Library/Preferences/org.pqrs.Karabiner-*

!$HOME/Library/Group Containers
$HOME/Library/Group Containers/*
!$HOME/Library/Group Containers/UBF8T346G9.*

!$HOME/Library/Containers
$HOME/Library/Containers/*
!$HOME/Library/Containers/com.microsoft.*
!$HOME/Library/Containers/com.anystonetech.*

!$HOME/Library/Application Support
$HOME/Library/Application Support/*
!$HOME/Library/Application Support/Alfred
!$HOME/Library/Application Support/BetterTouchTool
!$HOME/Library/Application Support/com.operasoftware.Opera

!$HOME/Library/Application Support/Adobe
$HOME/Library/Application Support/Adobe/*
!$HOME/Library/Application Support/Adobe/Adobe PDF

$HOME/.Trash
$HOME/.local
$HOME/.pub-cache
$HOME/Music/Music
$HOME/Movies
cache
.cache
_cacache
Caches
"""


class EvRb:
    """Erez Volk's Restic Backup."""

    def parse_args(self) -> None:
        """Parse command-line arguments."""
        parser = argparse.ArgumentParser(
            description="Backup home (using restic) to an external volume",
        )
        parser.add_argument(
            "-v",
            "--volume",
            type=Path,
            help="Volume for backups",
        )
        parser.add_argument(
            "-x",
            "--exclude",
            type=str,
            nargs="*",
            help="Exclude list (case-insensitive)",
        )
        parser.add_argument(
            "-n",
            "--dry-run",
            action="store_true",
            help="List the files instead of copying them",
        )
        parser.add_argument(
            "-y",
            "--yes",
            action="store_true",
            help="Don't wait",
        )
        args = parser.parse_args()
        self.parser = parser
        self.args = args

    args: argparse.Namespace
    parser: argparse.ArgumentParser
    root: Path

    def run(self) -> None:
        """Incremental backup to external volume."""
        self.parse_args()
        self.find_root()
        self.backup()

    def fail(self, message: str) -> t.Never:
        """Fail and exit."""
        self.parser.error(message)

    def find_root(self) -> None:
        """Figure out where to backup to."""
        if self.args.volume:
            if not self.args.volume.is_dir():
                self.fail("Invalid volume")
            root = self.args.volume / "restic"
        else:
            for volume in Path("/Volumes").glob("*"):
                if (root := volume / "restic").is_dir():
                    break
            else:
                self.fail("Please specify --volume")

        self.root = root
        if not root.is_dir():
            print(f"Creating {root}/")
            self.restic(["init"])

    def backup(self) -> None:
        """Run restic."""
        with TemporaryDirectory() as td:
            args = [
                "backup",
                Path.home(),
                "--verbose",
                "--exclude-caches",
                "--exclude-cloud-files",
            ]
            if self.args.exclude:
                for item in self.args.exclude:
                    args.extend(["--iexclude", str(item)])
            else:
                exclude_file = Path(td) / "exclude.txt"
                exclude_file.write_text(os.path.expandvars(EXCLUDE))
                args.extend(["--iexclude-file", str(exclude_file)])
            if self.args.dry_run:
                args.append("--dry-run")
            self.restic(args)

    def restic(self, args: list[str | Path]) -> None:
        """Call restic."""
        args = [
            "/usr/bin/caffeinate",
            "restic",
            "--repo",
            str(self.root),
            "--insecure-no-password",
            *map(str, args),
        ]
        print(" ".join(shlex.quote(str(arg)) for arg in args))
        input("Press Enter to run...")
        subprocess.run(args, check=True)


if __name__ == "__main__":
    EvRb().run()
