#!/bin/sh

# Update Git repo and pull if safe, and watch the traffic
# Based on https://stackoverflow.com/a/3278427

git remote update --prune

REMOTE=`git rev-parse @{u}`
if [ $? -ne 0 ]; then
    exit
fi

LOCAL=`git rev-parse @`
BASE=`git merge-base $LOCAL $REMOTE`

if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
    if [ $LOCAL = $REMOTE ]; then
        # echo "Up-to-date."
        exit 0
    elif [ $LOCAL = $BASE ]; then
        git merge --ff-only $REMOTE
    elif [ $REMOTE = $BASE ]; then
        echo "Need to push."
    else
        echo "Diverged."
    fi
else
    echo "Uncommitted changes."
fi
