#!/usr/bin/env python3
# something like git debranch; git pull --ff
from subprocess import run
from subprocess import PIPE
import re
import sys


def git(cmd, echo=True, check=True, **kwargs):
    if echo:
        print(f'>>> git {cmd}')

    output = run(f'git {cmd}', shell=True, **kwargs)
    if check:
        if output.returncode != 0:
            sys.exit(output.returncode)
    return output


def git_out(cmd):
    return git(cmd, echo=False, stdout=PIPE).stdout.decode()


def git_oneliner(cmd):
    return git_out(cmd).strip()


def git_lines(cmd):
    return git_out(cmd).split('\n')


git('fetch --prune --all --jobs=2', echo=False)
branches = git_lines('branch -vv')

current = None
goners = []

for line in branches:
    if not line:
        continue
    m = re.match(
        r'(?P<star>.) '
        r'(?P<name>.*\S)\s+'
        r'(?P<hash>[0-9a-f]{5,})\s'
        r'(?P<remote_clause>\[(?P<remote>\S+)(: (?P<gone>.*))?\])?'
        r'.*',
        line
    )
    if not m:
        print(f'UNKNOWN LINE: {line}')
        continue
    branch = m.group('name')
    remote = m.group('remote')
    gone = m.group('gone') == 'gone'
    if m.group('star') == '*':
        if branch.startswith('(HEAD deatched at'):
            print(f'{branch}: Not pulling')
        elif gone:
            print(f'{branch}: Remote branch gone, not pulling')
        else:
            current = m.group('remote')
    elif gone:
        goners.append(branch)


if current:
    local_hash = git_oneliner('rev-parse HEAD')
    remote_hash = git_oneliner(f'rev-parse {current}')
    common_hash = git_oneliner(f'merge-base HEAD {current}')
    if common_hash != remote_hash:
        git(f'merge --ff-only {current}')

if goners:
    goners = ' '.join(goners)
    git(f'branch -D {goners}')
