#!/usr/bin/env python3
from argparse import ArgumentParser
from random import randrange


def main():
    parser = ArgumentParser()
    parser.add_argument("-n", "--days", type=int, default=5)
    parser.add_argument("--minutes-per-day", type=int, default=8 * 60 + 30)
    parser.add_argument("--mean-start-hour", type=int, default=9)
    parser.add_argument("--start-margin", type=int, default=60)
    parser.add_argument("--duration-margin", type=int, default=60)
    args = parser.parse_args()

    mean_start_mins = args.mean_start_hour * 60
    total_mins = args.minutes_per_day * args.days
    for day in range(1, args.days):
        start = wiggle(mean_start_mins, args.start_margin)
        duration = wiggle(args.minutes_per_day, args.duration_margin)
        print(
            f"Day {day}: from {hhmm(start)} to {hhmm(start + duration)}, {hhmm(duration)}"
            f" ({duration - args.minutes_per_day:+d})"
        )
        total_mins -= duration

    start = wiggle(mean_start_mins, args.start_margin)
    duration = total_mins
    print(
        f"Day {args.days}: from {hhmm(start)} to {hhmm(start + duration)}, {hhmm(duration)}"
        f" ({duration - args.minutes_per_day:+d})"
    )


def wiggle(base, margin):
    return randrange(base - margin, base + margin + 1)


def hhmm(mmmm):
    hh, mm = divmod(mmmm, 60)
    return f"{hh:02d}:{mm:02d}"


if __name__ == "__main__":
    main()
