#!/bin/sh
echo "[keep]"
echo "HB's scales"
echo
pmp -d keep -n 3 -i 0
echo
pmp -d chops-l -n 1
pmp -d chops-r -n 1
echo
pmp -d arp
echo
echo "[proceed]"
pmp -d book -n 1
echo
echo "[maybe revise]"
pmp -d revise -n 1 -i 0
