#!/bin/sh
pmp -d steve-warmup -n 3 -i 0
echo
pmp -d steve-hazard
echo
pmp -d chops-l -n 1
pmp -d chops-r -n 1
echo
pmp -d arp
echo
echo "[Feeling Steve-y?]"
pmp -d steve-drill -n 1
pmp -d steve-etude -n 1
