#!/bin/sh
[ -f ~/.ooo-no-brew-upgrade ] || brew upgrade
if [ -f ~/.oooroots ]; then
	while read r; do
		git -C $HOME/"$r" oo
	done < ~/.oooroots
fi
bing-wallpaper
if which ggev > /dev/null; then
	ggev
fi
if which ooo-extra > /dev/null; then
	ooo-extra
fi
