#!/bin/sh
if [ -f ~/.ooo-brew-upgrade-cask ]; then
	brew upgrade --no-ask --cask
elif [ ! -f ~/.ooo-no-brew-upgrade ]; then
	brew upgrade --no-ask
fi

which port > /dev/null && [ ! -f ~/.ooo-no-port-update ] && sudo port selfupdate

if [ -f ~/.oooroots ]; then
	while read r; do
		git -C $HOME/"$r" oo
	done < ~/.oooroots
fi
bing-wallpaper
if which ggev > /dev/null; then
	ggev
fi
if which ooo-extra > /dev/null; then
	ooo-extra
fi
