#!/usr/bin/env python3
from argparse import ArgumentParser
from pathlib import Path
import random

import fitz  # pip install pymupdf


def main():
    parser = ArgumentParser()
    parser.add_argument("input", type=Path, help="PDF file to shuffle")
    parser.add_argument(
        "output", type=Path, nargs="?", help="Shuffled PDF file to create"
    )
    args = parser.parse_args()

    infn = args.input
    if args.output:
        outfn = args.output
    else:
        outfn = infn.with_stem(f"{infn.stem}-shuffled")

    print(f"{infn} -> {outfn}")
    TOP_OF_PAGE = fitz.Point(0, 0)

    indoc = fitz.Document(infn)
    n_pages = indoc.page_count
    if n_pages < 2:
        print(f"Not enough pages ({n_pages}) in document")
        return

    toc = indoc.get_toc(simple=False)
    bookmarks = list(sorted([
        entry[2] - 1  # ToC entries are 1-based
        for entry in toc
        if entry[3].get("to") == TOP_OF_PAGE
    ]))
    if bookmarks[0] != 0:
        bookmarks.insert(0, 0)
    if len(bookmarks) < 2:
        print(f"Not enough bookmarks ({len(bookmarks)}) in document")
        return

    bookmarks.append(n_pages)
    spans = list(zip(bookmarks[:-1], bookmarks[1:]))
    random.shuffle(spans)

    outdoc = fitz.Document()

    for nspan, (span_from, span_to) in enumerate(spans, 1):
        from_page = span_from
        to_page = span_to - 1
        while to_page > from_page and not indoc.get_page_fonts(to_page):
            to_page = to_page - 1
        outdoc.insert_pdf(indoc, from_page, to_page, final=nspan == len(spans))
    outdoc.ez_save(outfn)


if __name__ == "__main__":
    main()
