#!/usr/bin/env python3
"""Pretty-print JSON."""
import argparse
import json
from pathlib import Path
from tempfile import TemporaryDirectory


def usage() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "inputs",
        metavar="JSON_FILE",
        type=Path,
        nargs="+",
    )
    parser.add_argument(
        "-B",
        "--no-backup",
        action="store_true",
    )
    return parser.parse_args()


class PpJson:
    """Pretty-print JSON."""

    def run(self) -> None:
        """Pretty-print JSON."""
        args = usage()

        with TemporaryDirectory() as tdir:
            tpath = Path(tdir) / "pretty.json"
            for path in args.inputs:
                print(path)
                try:
                    with path.open("rb") as fobj:
                        obj = json.load(fobj)
                except json.JSONDecodeError:
                    print(" -> Cannot decode JSON")
                if not args.no_backup:
                    path.copy(path.with_name(f"{path.name}.bak"))
                with tpath.open("w", encoding="utf-8") as fobj:
                    json.dump(obj, fobj, ensure_ascii=False, indent=2)
                tpath.copy(path)


if __name__ == "__main__":
    PpJson().run()
