#!/usr/bin/env python3
from argparse import ArgumentParser
import xml.dom.minidom


def main():
    parser = ArgumentParser()
    parser.add_argument("xmls", metavar="XML_FILE", nargs="+")
    args = parser.parse_args()

    for xmlfn in args.xmls:
        dom = xml.dom.minidom.parse(xmlfn)
        pretty = dom.toprettyxml(indent="  ")
        with open(xmlfn, "w") as xmlfo:
            xmlfo.write(pretty)


if __name__ == "__main__":
    main()
