#!/usr/bin/env -S uv run --script
"""Pretty-print XML."""
from argparse import ArgumentParser
from pathlib import Path

from lxml import etree


def main() -> None:
    """Pretty-print XML."""
    parser = ArgumentParser()
    parser.add_argument("xmls", metavar="XML_FILE", nargs="+", type=Path)
    args = parser.parse_args()

    xmlfn: Path
    for xmlfn in args.xmls:
        try:
            print(f"Formatting {xmlfn}")
            with xmlfn.open("r") as xmlfo:
                doc = etree.parse(xmlfo)
            pretty = etree.tostring(
                doc,
                xml_declaration=True,
                encoding=doc.docinfo.encoding,
                standalone=doc.docinfo.standalone,
                pretty_print=True,
            )
            xmlfn.write_bytes(pretty)
        except (FileNotFoundError, PermissionError, etree.XMLSyntaxError) as exc:
            print(f"ERROR IN {xmlfn}: {exc}")


if __name__ == "__main__":
    main()

# /// script
# dependencies = ["lxml"]
# ///
# vim: set ft=python:
