#!/usr/bin/env python3
"""Spleet audio files by silence."""
import argparse
import typing as t
import re
from pathlib import Path

import numpy as np
import numpy.typing as npt
import pandas as pd
from pydub import AudioSegment


SplitPoint: t.TypeAlias = float | int
SplitList: t.TypeAlias = list[SplitPoint]


class Runs(t.NamedTuple):
    """A list of same-value runs."""

    values: np.ndarray
    starts: np.ndarray
    lengths: np.ndarray


class Spleet:
    """Spleet audio files by silence."""

    args: argparse.Namespace
    min_ms: int
    sus: set[Path]

    def main(self) -> None:
        """Spleet."""
        self.sus = set()
        for path in self.parse_args():
            self.spleet(path)
        if self.sus:
            print(
                "You may want to check:",
                " ".join(path.name for path in self.sus),
            )

    def parse_args(self) -> None:
        """Parse command line."""
        parser = argparse.ArgumentParser(
            description="Split audio files by silence",
            formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        )
        parser.add_argument(
            "-m",
            "--mean",
            metavar="MM[:SS]",
            type=self.mmss_to_ms,
            default="2:00",
            help="Aim for mean split duration",
        )
        parser.add_argument(
            "--slice-ms",
            type=int,
            default=50,
            help="Used for silence estimation",
        )
        parser.add_argument(
            "--top-quantile",
            type=float,
            default=0.99,
            help="Used for silence estimation",
        )
        parser.add_argument(
            "--threshold-nth",
            type=int,
            default=32,
            help="Used for silence estimation",
        )
        parser.add_argument(
            "--wiggle-nth",
            type=int,
            default=4,
            help="Used for split point search",
        )
        parser.add_argument(
            "-o",
            "--output",
            type=Path,
            help="Write output script",
        )
        parser.add_argument(
            "files",
            metavar="MP3_FILE",
            nargs="+",
            type=Path,
            help="Input file",
        )
        self.args = parser.parse_args()
        self.min_ms = self.args.mean // self.args.wiggle_nth
        return self.args.files

    def spleet(self, path: Path) -> None:
        """Process one audio file."""
        points_ms = self.get_splitlist(path)
        if any(np.isnan(ms) for ms in points_ms):
            self.sus.add(path)

        points_text = [self.ms_to_mp3splt(ms) for ms in points_ms]
        points = " ".join(points_text)
        line = (
            f"mp3splt -f -n -d '.' -o '@f/@f @n2' '{path}' "
            f"0.00 {points} EOF"
        )
        print(line)
        if not self.args.output:
            return

        existed = self.args.output.is_file()
        with self.args.output.open("a+t", encoding="utf-8") as fobj:
            fobj.write(line)
            fobj.write("\n")
        if not existed:
            self.args.output.chmod(0o755)

    @classmethod
    def ms_to_mp3splt(cls, msec: SplitPoint) -> str:
        """Convert number to the time format used by mp3splt."""
        if np.isnan(msec):
            return ""

        secs, millis = divmod(msec, 1000)
        mins, secs = divmod(secs, 60)
        if millis == 0:
            return f"{mins}.{secs:02d}"

        return f"{mins}.{secs:02d}.{millis // 10:02d}"

    @classmethod
    def mmss_to_ms(cls, mmss: str) -> int:
        """Convert MIN:SEC string like '1:20' to milliseconds (80000)."""
        if not (match := re.match(r"^(\d+):(\d\d)$", mmss)):
            raise argparse.ArgumentTypeError

        return (int(match.group(1)) * 60 + int(match.group(2))) * 1000

    def get_splitlist(self, path: Path) -> SplitList:
        """Find where to split."""
        snd = AudioSegment.from_file(path)
        duration_ms = len(snd)
        if duration_ms <= self.args.mean + self.min_ms:
            return []

        sliceable_ms = (len(snd) // self.args.slice_ms) * self.args.slice_ms
        rmss = np.array([
            snd[start_ms : start_ms + self.args.slice_ms].rms
            for start_ms in range(0, sliceable_ms, self.args.slice_ms)
        ])
        threshold_times_n = np.quantile(rmss, self.args.top_quantile)
        threshold = threshold_times_n / self.args.threshold_nth
        vads = rmss > threshold

        runs = self.find_runs(vads)
        sil_tmap = runs.to_numpy() == 0
        sils = pd.DataFrame({
            "start": runs.starts[sil_tmap] * self.args.slice_ms,
            "length": runs.lengths[sil_tmap] * self.args.slice_ms,
        })
        sils["end"] = sils.start + sils.length

        return self.sils_to_list(sils, duration_ms)

    def sils_to_list(self, sils: pd.DataFrame, duration_ms: int) -> SplitList:
        """Find split points from silences."""
        points = []
        target = self.args.mean
        limit_ms = duration_ms - self.min_ms
        while target <= limit_ms:
            window_min = target - self.min_ms
            window_max = target + self.min_ms
            rows = sils.query(f"start < {window_max} and end > {window_min}")
            if len(rows) == 0:
                point = np.nan
            else:
                row = rows.loc[rows.length.idxmax()]
                if row.length > self.args.slice_ms:
                    point = row.end - self.args.slice_ms
                else:
                    point = (row.start + row.end) // 2
                if point > limit_ms:
                    point = np.nan

            points.append(point)
            target = point + self.args.mean

        return points

    @classmethod
    def find_runs(cls, arr: npt.ArrayLike) -> Runs:
        """Find runs of consecutive items in an array.

        https://gist.github.com/alimanfoo/c5977e87111abe8127453b21204c1065
        """
        # ensure array
        arr = np.asanyarray(arr)
        if arr.ndim != 1:
            raise ValueError("only 1D array supported")
        nvals = arr.shape[0]

        # handle empty array
        if nvals == 0:
            return Runs(np.array([]), np.array([]), np.array([]))

        # find run starts
        loc_run_start = np.empty(nvals, dtype=bool)
        loc_run_start[0] = True
        np.not_equal(arr[:-1], arr[1:], out=loc_run_start[1:])
        run_starts = np.nonzero(loc_run_start)[0]

        # find run values
        run_values = arr[loc_run_start]

        # find run lengths
        run_lengths = np.diff(np.append(run_starts, nvals))

        return Runs(run_values, run_starts, run_lengths)


if __name__ == "__main__":
    Spleet().main()
