#!/bin/sh
WORKDIR=`mktemp -d`
cd "$WORKDIR"

cleanup() {
	cd
	rm -Rfv "$WORKDIR"
}
trap cleanup EXIT

for i in "$@"; do
	yt-dlp --extract-audio --audio-format mp3 --embed-metadata "$i"
done

bold=$(tput bold)
offbold=$(tput sgr0)

echo "${bold}After Anytune loads, kill this script${offbold} to delete $WORKDIR"
open -a Anytune -W *.mp3
