#!/bin/sh
yt-dlp --write-thumbnail --extract-audio --embed-metadata --embed-metadata --parse-metadata "playlist_index:%(track_number)s" --audio-format mp3 --print-to-file "%(playlist_index)s %(title)s.%(ext)s" "%(playlist)s/%(playlist_title)s.m3u" -o "%(playlist)s/%(playlist_index)s %(title)s [%(id)s].%(ext)s" "$@"
